"""Add light table

Revision ID: 427af97aeb1f
Revises: 
Create Date: 2022-06-14 20:21:09.224507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427af97aeb1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osc_light', sa.Column('description', sa.String(), nullable=True))
    op.add_column('osc_light', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('osc_light', 'is_default')
    op.drop_column('osc_light', 'description')
    # ### end Alembic commands ###
