"""Add btn_id to fs_btn table

Revision ID: cf609a4794ac
Revises: de3b785ed708
Create Date: 2022-06-28 21:24:30.436211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf609a4794ac'
down_revision = 'de3b785ed708'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fs_buttons', sa.Column('btn_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fs_buttons', 'btn_id')
    # ### end Alembic commands ###
