"""Add FS table, light columns

Revision ID: de3b785ed708
Revises: 
Create Date: 2022-06-21 18:44:26.365362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3b785ed708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('footswitch',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fs_buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('has_led', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('action_cat', sa.String(), nullable=True),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('fs_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['fs_id'], ['footswitch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fs_buttons_id'), 'fs_buttons', ['id'], unique=False)
    op.add_column('osc_light', sa.Column('description', sa.String(), nullable=True))
    op.add_column('osc_light', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('osc_light', 'is_default')
    op.drop_column('osc_light', 'description')
    op.drop_index(op.f('ix_fs_buttons_id'), table_name='fs_buttons')
    op.drop_table('fs_buttons')
    op.drop_table('footswitch')
    # ### end Alembic commands ###
